# utils/check_pt.py
import torch
from pathlib import Path
import numpy as np  # For checking NaNs/Infs


def validate_pt_file(pt_file_path: str):
    print(f"🔍 Validating .pt file: {pt_file_path}")
    if not Path(pt_file_path).is_file():
        print(f"❌ Error: File not found: {pt_file_path}")
        return

    try:
        data = torch.load(pt_file_path, map_location="cpu")
        print(f"✅ Loaded: {pt_file_path}")
    except Exception as e:
        print(f"❌ Error loading .pt file: {e}")
        return

    if not isinstance(data, dict):
        print(f"⚠️ Expected a dictionary in .pt file, but found type: {type(data)}")
        return

    print("\n--- Contents ---")
    for key, value in data.items():
        if isinstance(value, torch.Tensor):
            # --- CORRECTED LINE ---
            print(f"Key: {key:<25} Shape: {str(tuple(value.shape)):<20} Dtype: {value.dtype}")
            # --- END OF CORRECTION ---
            if value.dtype.is_floating_point:
                num_nans = torch.isnan(value).sum().item()
                num_infs = torch.isinf(value).sum().item()
                if num_nans > 0:
                    print(f"    ⚠️ Contains {num_nans} NaN(s)!")
                if num_infs > 0:
                    print(f"    ⚠️ Contains {num_infs} Inf(s)!")
                # Optional: Print min/max for numerical tensors
                # if value.numel() > 0: # Check if tensor is not empty
                #     # Handle all-NaN or all-Inf tensors for min/max
                #     finite_values = value[torch.isfinite(value)]
                #     if finite_values.numel() > 0:
                #         print(f"        Min (finite): {torch.min(finite_values):.4f}, Max (finite): {torch.max(finite_values):.4f}")
                #     else:
                #         print(f"        Min/Max: No finite values found in tensor.")

        elif isinstance(value, dict):
            print(f"Key: {key:<25} Type: dict, Items (first 3): {dict(list(value.items())[:3])}...")
        else:
            print(f"Key: {key:<25} Type: {type(value)}, Value (sample): {str(value)[:100]}")


# Example of how you might call it in your check_pt.py's __main__
if __name__ == "__main__":
    # This should point to the .pt file generated by your flow preprocessing
    # For example, the one that your finetune.py is trying to load
    # Example: target_pt_file_to_check = "../../../dataset/processed_flows.pt"

    # **** USER: Set this to the actual .pt file you want to check ****
    # Ensure this path is correct relative to where check_pt.py is run from
    target_pt_file_to_check = "../../../dataset/processed_flows.pt"  # Or your mini_flow.pt etc.

    if Path(target_pt_file_to_check).exists():
        validate_pt_file(target_pt_file_to_check)
    else:
        print(f"File to check does not exist: {target_pt_file_to_check}")
        print("Please update 'target_pt_file_to_check' at the end of utils/check_pt.py")
